import java.util.Scanner;

class tabledeclaration{
    public static void main(String[]args){
        Scanner val=new Scanner(System.in);
        String str1;
        String str2;
        String str3;
        int total1;
        int total2;
        int total3;
        char grade1;
        char grade2;
        char grade3;
        float cgpa1;
        float cgpa2;
        float cgpa3;
        boolean res1;
        boolean res2;
        boolean res3;
        System.out.print("Enter a Ur Name 1 : ");
        str1=val.nextLine();
        System.out.print("Enter Ur TOTAL Mark 1 : ");
        total1=val.nextInt();
        System.out.print("Enter Ur GRADE Mark 1 : ");
        grade1=val.next().charAt(0);
        System.out.print("Enter Ur CGPA Mark 1 : ");
        cgpa1=val.nextFloat();
        System.out.print("Enter Ur Result 1 :");
        res1=val.nextBoolean();
        str2=val.nextLine();
        System.out.print("Enter a Ur Name 2 : ");
        str2=val.nextLine();
        System.out.print("Enter Ur TOTAL Mark 2 : ");
        total2=val.nextInt();
        System.out.print("Enter Ur GRADE Mark 2 : ");
        grade2=val.next().charAt(0);
        System.out.print("Enter Ur CGPA Mark 2 : ");
        cgpa2=val.nextFloat();
        System.out.print("Enter Ur Result 2 :");
        res2=val.nextBoolean();
        str3=val.nextLine();
        System.out.print("Enter a Ur Name 3 : ");
        str3=val.nextLine();
        System.out.print("Enter Ur TOTAL Mark 3 : ");
        total3=val.nextInt();
        System.out.print("Enter Ur GRADE Mark 3 : ");
        grade3=val.next().charAt(0);
        System.out.print("Enter Ur CGPA Mark 3 : ");
        cgpa3=val.nextFloat();
        System.out.print("Enter Ur Result 3 :");
        res3=val.nextBoolean();
        System.out.println(str1);
        System.out.println(total1);
        System.out.println(grade1);
        System.out.println(cgpa1);
        System.out.println(str2);
        System.out.println(total2);
        System.out.println(grade2);
        System.out.println(cgpa2);
        System.out.println(str3);
        System.out.println(total3);
        System.out.println(grade3);
        System.out.println(cgpa3);
        System.out.println(res1);
        System.out.println(res2);
        System.out.println(res3);
        System.out.println("|STUDENT NAME\t|TOTAL MARK\t|GRADE\t|CGPA\t|RESULT|");
        System.out.println("_________________________________________________");
        System.out.println(str1+ "\t\t|"+total1 + "\t|" + grade1 + "\t|"+cgpa1 + "\t|"+res1);
        System.out.println("-------------------------------------------------");
        System.out.println(str2+ "\t\t|"+total2 + "\t|" + grade2 + "\t|"+cgpa2 + "\t|"+res2);
        System.out.println("-------------------------------------------------");
        System.out.println(str3+ "\t\t|"+total3 + "\t|" + grade3 + "\t|"+cgpa3 + "\t|"+res3);
        System.out.println("-------------------------------------------------");
        // tamil=56;
        // english=80;
        // maths=44;
        // System.out.println("ASHIF         "+tamil + "       |        " + english + "      |        "+maths + "     |        ");
        // System.out.println("-------------------------------------------------");
        // tamil=54;
        // english=90;
        // maths=39;

        // System.out.println("VISHNU        "+tamil + "       |        " + english + "      |        "+maths + "     |        ");
        // System.out.println("-------------------------------------------------");
        
    }
}